apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

resources:
  - kafka-connect-build.yml # kafka connect pod config

  # topics
  - topic/auth-service-topic.yml
  - topic/booking-service-topic.yml
  - topic/payment-service-topic.yml

  # connectors
  - connect/auth-db-connector.yml
  - connect/booking-db-connector.yml
  - connect/payment-db-connector.yml
