spring:
  application:
    name: auth-service
  cloud:
    config:
      fail-fast: true
#      uri: http://${config-server.address}:${config-server.port}
#      username: ${CLOUD_CONFIG_USERNAME}
#      password: ${CLOUD_CONFIG_PASSWORD}
      profile: prod
      label: main

#  config:
#    import: "optional:configserver:http://localhost:8888/" # <--- calling to Config Server
