---
# Service: Internal Networking
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: default
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8888       # The port other K8s pods will call
      targetPort: 8888 # The port your Java app runs on inside the container
  type: ClusterIP      # Internal traffic only

---
# Deployment: The Pod & Image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          # Using the Monorepo Tagging strategy!
          image: registry.digitalocean.com/cinemesh-registry-truongbb/cinemesh:config-server-v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi" # K8s limits the container RAM
              cpu: "500m"
          env:
            # Tells Spring to use application-kubernetes.yml from your Git repo
            - name: SPRING_PROFILES_ACTIVE
              value: "git"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: "https://github.com/truongbb/cinemesh.git"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL
              value: "main"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS
              value: "config-files"

            # Inject the Git Username
            - name: GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cinemesh-secrets
                  key: GIT_USERNAME

            # Inject the Git Token
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cinemesh-secrets
                  key: GIT_TOKEN


