---
# Service: Internal Networking (The "Company Way")
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: default
spec:
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 80         # 🌟 Kong calls this clean port
      targetPort: 8080 # 🌟 K8s secretly forwards it to Spring Boot on 8080
  type: ClusterIP
