apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

resources:
  - kafka-connect-build.yml # kafka connect pod config

  # topics
  - topic/user-logs-topic.yml

  # connectors
  - connect/auth-db-connector.yml
