application:
  security:
    accessToken:
      secretKey: e3f0acd51fe8f38b145c82074ac46abf3395db7ad3eb1a96166d31c35409b14fe7725d18bd177d860caaceb17decdc5a704c0ecc91a8e40ac4b5168e9a0af10e
      tokenValidityMilliseconds: 900000
    refreshToken:
      secretKey: e3f0acd51fe8f38b145c82074ac46abf3395db7ad3eb1a96166d31c35409b14fe7725d18bd177d860caaceb17decdc5a704c0ecc91a8e40ac4b5168e9a0af10e
      tokenValidityMilliseconds: 1800000

feign:
  domain:
    auth-service: localhost:9999 # domain API gateway
    movie-service: localhost:9999
    theater-service: localhost:9999
    booking-service: localhost:9999

spring:
  output:
    ansi:
      enabled: ALWAYS # Forces IntelliJ/Terminal to render the colors

logging:
  pattern:
    # We wrap different sections in %clr(){color_name}
    # Level gets auto-colored (INFO=green, ERROR=red)
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%-5level) %clr([%X{requestId}]){magenta} %clr(---){faint} %clr([%15.15thread]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %msg%n"


