server:
  port: 9005

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:54321/cinemesh_payment_db
    username: cinemesh
    password: '{cipher}85afe47df2b242740712388acc200673e4afe7d1194f3e826efdd1c3dfdb5761'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # <--- Eureka address

application:
  vn-pay:
    tmn-code: 1SPYFLH1
    hash-secret: ZQB2T4GNXE015WNJTLIGT1OYKZT4B8RR
    pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: http://localhost:3000
  kafka:
    payment-notification: # lắng nghe message quyét từ bảng payment-notification của auth-service
      bootstrap-server: localhost:9092 # Or kafka:29092 if inside Docker
      topic: cinemesh.payment-service.payment-notification
      group-id: payment-notification-dev
      retry-interval: 2000 #Khoảng thời gian giữa các lần lặp
      retry-multiplier: 2 #Hệ số tăng thời gian
      retry-max-interval: 10000 #Khoảng thời gian lớn nhất giữa các lần lặp
      retry-max-attempts: 2 #Số lần lặp lại công việc nếu xảy ra lỗi
      ignored: false #Có bỏ qua hay không (commit và đi tiếp)?
      reproduced: false #Có đẩy sang topic khác không?
      reproduce-topic: cinemesh.payment-service.payment-notification
      stopped: true #Dừng lại khi xử lý lỗi message và đã thực hiện xử lý lại message nếu có.
      auto-startup: true #Tự động startup kafka consumer
