server:
  port: 9005

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:54321/cinemesh_payment_db
    username: cinemesh
    password: 'cinemesh123!@#'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # <--- Eureka address

application:
  vn-pay:
    tmn-code: 1SPYFLH1
    hash-secret: ZQB2T4GNXE015WNJTLIGT1OYKZT4B8RR
    pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: http://localhost:3000
